---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# dhsmmrdemo

<!-- badges: start -->
<!-- badges: end -->

The goal of dhsmmrdemo is to demostrate the package development process in r enviroment. 

## Installation

You can install the development version of dhsmmrdemo from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("dhsmyanmar/dhsmmrdemo")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(dhsmmrdemo)

## basic example code
# HAZ mean score
haz_score <- get_haz(PRdata$hv103, PRdata$hc70)

wt <- PRdata$hv005/1000000

weighted.mean(haz_score, wt, na.rm = TRUE)

summary(haz_score, na.rm = TRUE)

# stunting
stunting <- get_stunt(haz_score)
xtabs(wt ~ stunting)
sum(xtabs(wt ~ stunting))
prop.table(xtabs(wt ~ stunting))
   
```

